Rework multi acquire
nion-software/nionswift-instrumentation-kit pull request #46
Opened 2020-10-28 09:27 UTC by Brow71189

I think you had some comments on the reworked code which is why we did not merge the changes yet. I'm just opening this so that we don't forget about it.

2020-11-11 16:05 UTC, cmeyer commented
Is this ready for review or still a work in progress? (We can mark it as a 'draft' if it's still in progress in the Reviewers section at the top-right of this web page).

2020-11-11 16:53 UTC, Brow71189 commented
It is ready by itself an contains hooks for implementing drift correction.
Just actually implementing drift correction will need more planning and
diacussion.

Chris Meyer <notifications@github.com> schrieb am Mi., 11. Nov. 2020, 17:05:

> Is this ready for review or still a work in progress? (We can mark it as a
> 'draft' if it's still in progress in the Reviewers section at the top-right
> of this web page).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nion-software/nionswift-instrumentation-kit/pull/46#issuecomment-725509007>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7SKKYA4ILSGW4NQ52UXPDSPKY4BANCNFSM4TCBWZEA>
> .
>

2020-11-17 00:25 UTC, cmeyer requested changes
Overall this PR looks good - much cleaner code than before.

There is one outstanding issue - I think ScanDataChannel should be a standalone class, not derived from SynchronizedDataChannelInterface. The 'update' method conflicts in the type checker.

Is it ok to squash these changes into a single commit? Or rebase to consolidate the commits into 1-3 commits? If you don't have any opinion, I'll just squash before merging.

Also, no changes required for this PR, but one thing that would be useful in the future is to run it through mypy and flake8 for type checking and formatting.

2020-11-17 00:25 UTC, cmeyer commented on nion/instrumentation/MultiAcquire.py
> +class ScanDataChannel(scan_base.SynchronizedDataChannelInterface):
I don't think this should be derived from scan_base.SynchronizedDataChannelInterface, which is for cameras. The 'update' method conflicts in my type checker.

2020-11-17 18:50 UTC, cmeyer commented
Merged 3500de95717663ce341b4534d184b56b5df2133d

2020-11-17 18:50 UTC, closed without merging